// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUuXOeFNMDdb9ZY20JnTUTpnsF52kgnl8',
    appId: '1:898844326925:web:066facbf6e7e682ebf6944',
    messagingSenderId: '898844326925',
    projectId: 'dse-kai',
    authDomain: 'dse-kai.firebaseapp.com',
    databaseURL: 'https://dse-kai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dse-kai.firebasestorage.app',
    measurementId: 'G-KJXP0S7586',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKDX8vvwGcDKE_orUoQVoeozImUoANvF0',
    appId: '1:898844326925:android:ea51f0c1fa0d1f59bf6944',
    messagingSenderId: '898844326925',
    projectId: 'dse-kai',
    databaseURL: 'https://dse-kai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dse-kai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6vNoWxNcXkAMvdU077MYN7cor82rpVx4',
    appId: '1:898844326925:ios:5092bda499b823a5bf6944',
    messagingSenderId: '898844326925',
    projectId: 'dse-kai',
    databaseURL: 'https://dse-kai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dse-kai.firebasestorage.app',
    iosBundleId: 'com.example.newKai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6vNoWxNcXkAMvdU077MYN7cor82rpVx4',
    appId: '1:898844326925:ios:5092bda499b823a5bf6944',
    messagingSenderId: '898844326925',
    projectId: 'dse-kai',
    databaseURL: 'https://dse-kai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dse-kai.firebasestorage.app',
    iosBundleId: 'com.example.newKai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUuXOeFNMDdb9ZY20JnTUTpnsF52kgnl8',
    appId: '1:898844326925:web:a58b2bd666480ec5bf6944',
    messagingSenderId: '898844326925',
    projectId: 'dse-kai',
    authDomain: 'dse-kai.firebaseapp.com',
    databaseURL: 'https://dse-kai-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dse-kai.firebasestorage.app',
    measurementId: 'G-PBEMZ3FMWF',
  );

}